version: '3.3'
services:

  post_db:
    image: "mongo:${mongodb_version:-latest}"
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
              - comment_db

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
        - front_net


  ui:
    image: "${USERNAME}/ui:${ui_version:-2.2}"
    ports:
      - "${ui_exposed_web:-9292}:9292/tcp"
    networks:
      - front_net

  post:
    image: "${USERNAME}/post:${post_version:-2.2}"
    networks:
      - back_net
      - front_net

  comment:
    image: "${USERNAME}/comment:${comment_version:-2.2}"
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
