---

- name: install some system dependecies
  apt:
    name: "{{ item }}"
  loop: "{{ deps_list }}"

- name: install software from repository
  apt:
    name: "{{ item }}"
  loop: "{{ install_list }}"

- name: copy bin from web
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  loop: "{{ copy_from_web_list }}"

- name: Get cfssl
  get_url:
    url: "{{ cfssl_url }}"
    dest: /usr/local/bin/cfssl
    mode: 0755
- name: Get cfssljson
  get_url:
    url: "{{ cfssl_json_url }}"
    dest: /usr/local/bin/cfssljson
    mode: 0755
