---
apiVersion: v1
kind: Service
metadata:
  name:  {{ template "post.fullname" . }}
  labels:
    app: reddit
    component: post
    release: {{ .ReleaseName }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: post
    release: {{ .Release.Name }}
